### ISSUE TITLE
Exception in Fields property of ContextualType

### ISSUE THREAD

**Issue by vvdb-architecture** [RicoSuter/Namotion.Reflection#157]
Consider the following definition:

~~~csharp
        class Base
        {
            public int Field1;
        }

        class Derived<T> : Base
        {
            public T? Field2;
        }
~~~

... then the following code will fail when the `Fields` property is called:

~~~csharp
            var ctype = typeof(Derived<int>).ToContextualType();
            foreach (var f in ctype.Fields)
            {
                Console.WriteLine(f.Name);
            }
~~~

The reason is explained in a frustrating NSwag bug reported here: https://github.com/RicoSuter/NSwag/issues/4842#issuecomment-2255506566

**Comment by Tomius** [comment]
There's a different, but closely related bug if it's the Base class that's generic and the DerivedClass isn't, e.g.

```
using Namotion.Reflection;

var fields = typeof(Derived).ToContextualType().Fields;

public class Base<T> { public T GenericField; }
public class Derived : Base<bool>;
```

throws:
```
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Namotion.Reflection.ContextualType.<get_Fields>b__36_0(FieldInfo field)
   at System.Linq.Enumerable.SelectArrayIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at Namotion.Reflection.ContextualType.get_Fields()
   at Program.<Main>$(String[] args) in C:\Code\ConsoleApp1\ConsoleApp1\Program.cs:line 8
```

This is because [this line](https://github.com/RicoSuter/Namotion.Reflection/blob/a4bc634631efa7b9078d07911be45cb2ab5e7bcb/src/Namotion.Reflection/Context/ContextualType.cs#L230C58-L230C74)
```
var actualType = GenericArguments[genericField.FieldType.GenericParameterPosition];
```
should be
```
var actualType = field.DeclaringType.GenericArguments[genericField.FieldType.GenericParameterPosition];
```
