### ISSUE TITLE
ContextualType.Properties fail when type is generic but not the declaring type of a property

### ISSUE THREAD

**Issue by billybraga** [RicoSuter/Namotion.Reflection#90]
Had this bug while using NJsonSchema.

Repro:

```csharp
        public class ParentClass
        {
            public string Property { get; set; }
        }

        public class GenericChildClass<T> : ParentClass
        {
        }

        public void Repro()
        {
            var ct = typeof(GenericChildClass<string>).ToContextualType()
            // this fails because the property's declaring type is not generic
            _ = ct.Properties;
        }
```

Here is the code that fails in `ContextualType.cs` because `property.DeclaringType` (`ParentClass`) isn't generic even if `GenericChildClass<string>` is. The call the `GetGenericTypeDefinition()` throws because `ParentClass` is not generic.

```csharp
                if (this.TypeInfo.IsGenericType && !this.TypeInfo.ContainsGenericParameters)
                {
                  PropertyInfo runtimeProperty = property.DeclaringType.GetGenericTypeDefinition().GetRuntimeProperty(property.Name);
```

**Comment by RicoSuter** [comment]
Ou so in the if we need the checks on property.DeclaringType instead of TypeInfo?

**Comment by billybraga** [comment]
Maybe... Honestly, I'm not sure exactly what this library does. I use it through NSwag, which uses NJsonSchema, which uses Namotion.Reflection...

**Comment by rhegner** [comment]
Since updating from NSwag 13.12.1 to 13.13.0 I get a similar Namotion exception:

```
System.InvalidOperationException: Method may only be called on a Type for which Type.IsGenericParameter is true.
 at System.RuntimeType.get_GenericParameterPosition()
 at Namotion.Reflection.ContextualType.<get_Properties>b__42_0(PropertyInfo property)
 at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
 at Namotion.Reflection.ContextualType.get_Properties()
 at Namotion.Reflection.ContextualTypeExtensions.GetContextualProperties(Type type)
 at NJsonSchema.Generation.JsonSchemaGenerator.ApplyAdditionalProperties[TSchemaType](TSchemaType schema, Type type, JsonSchemaResolver schemaResolver)
 at NJsonSchema.Generation.JsonSchemaGenerator.GenerateInheritance(ContextualType type, JsonSchema schema, JsonSchemaResolver schemaResolver)
 at NJsonSchema.Generation.JsonSchemaGenerator.GenerateObject(JsonSchema schema, JsonTypeDescription typeDescription, JsonSchemaResolver schemaResolver)
 at NSwag.Generation.OpenApiSchemaGenerator.GenerateObject(JsonSchema schema, JsonTypeDescription typeDescription, JsonSchemaResolver schemaResolver)
 at NJsonSchema.Generation.JsonSchemaGenerator.Generate[TSchemaType](TSchemaType schema, ContextualType contextualType, JsonSchemaResolver schemaResolver)
 at NJsonSchema.Generation.JsonSchemaGenerator.Generate[TSchemaType](ContextualType contextualType, JsonSchemaResolver schemaResolver)
 at NJsonSchema.Generation.JsonSchemaGenerator.Generate[TSchemaType](Type type, JsonSchemaResolver schemaResolver)
 at NJsonSchema.Generation.JsonSchemaGenerator.Generate(Type type, JsonSchemaResolver schemaResolver)
 at NSwag.Generation.OpenApiSchemaGenerator.GenerateObject(JsonSchema schema, JsonTypeDescription typeDescription, JsonSchemaResolver schemaResolver)
 at NJsonSchema.Generation.JsonSchemaGenerator.Generate[TSchemaType](TSchemaType schema, ContextualType contextualType, JsonSchemaResolver schemaResolver)
 at NJsonSchema.Generation.JsonSchemaGenerator.Generate[TSchemaType](ContextualType contextualType, JsonSchemaResolver schemaResolver)
 at NJsonSchema.Generation.JsonSchemaGenerator.Generate[TSchemaType](Type type, JsonSchemaResolver schemaResolver)
 at NJsonSchema.Generation.JsonSchemaGenerator.Generate(Type type, JsonSchemaResolver schemaResolver)
 at NJsonSchema.Generation.JsonSchemaGenerator.AddKnownType(Type type, JsonSchemaResolver schemaResolver)
 at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
 at NJsonSchema.Generation.JsonSchemaGenerator.GenerateKnownTypes(Type type, JsonSchemaResolver schemaResolver)
 at NJsonSchema.Generation.JsonSchemaGenerator.GenerateObject(JsonSchema schema, JsonTypeDescription typeDescription, JsonSchemaResolver schemaResolver)
 at NSwag.Generation.OpenApiSchemaGenerator.GenerateObject(JsonSchema schema, JsonTypeDescription typeDescription, JsonSchemaResolver schemaResolver)
 at NJsonSchema.Generation.JsonSchemaGenerator.Generate[TSchemaType](TSchemaType schema, ContextualType contextualType, JsonSchemaResolver schemaResolver)
 at NJsonSchema.Generation.JsonSchemaGenerator.Generate[TSchemaType](ContextualType contextualType, JsonSchemaResolver schemaResolver)
 at NJsonSchema.Generation.JsonSchemaGenerator.Generate[TSchemaType](Type type, JsonSchemaResolver schemaResolver)
 at NJsonSchema.Generation.JsonSchemaGenerator.Generate(Type type, JsonSchemaResolver schemaResolver)
 at NSwag.Generation.OpenApiSchemaGenerator.GenerateObject(JsonSchema schema, JsonTypeDescription typeDescription, JsonSchemaResolver schemaResolver)
 at NJsonSchema.Generation.JsonSchemaGenerator.Generate[TSchemaType](TSchemaType schema, ContextualType contextualType, JsonSchemaResolver schemaResolver)
 at NJsonSchema.Generation.JsonSchemaGenerator.Generate[TSchemaType](ContextualType contextualType, JsonSchemaResolver schemaResolver)
 at NJsonSchema.Generation.JsonSchemaGenerator.GenerateWithReferenceAndNullability[TSchemaType](ContextualType contextualType, Boolean isNullable, JsonSchemaResolver schemaResolver, Action`2 transformation)
 at NSwag.Generation.OpenApiSchemaGenerator.GenerateWithReferenceAndNullability[TSchemaType](ContextualType contextualType, Boolean isNullable, JsonSchemaResolver schemaResolver, Action`2 transformation)
 at NJsonSchema.Generation.JsonSchemaGenerator.GenerateArray[TSchemaType](TSchemaType schema, JsonTypeDescription typeDescription, JsonSchemaResolver schemaResolver)
 at NJsonSchema.Generation.JsonSchemaGenerator.Generate[TSchemaType](TSchemaType schema, ContextualType contextualType, JsonSchemaResolver schemaResolver)
 at NJsonSchema.Generation.JsonSchemaGenerator.Generate[TSchemaType](ContextualType contextualType, JsonSchemaResolver schemaResolver)
 at NJsonSchema.Generation.JsonSchemaGenerator.GenerateWithReferenceAndNullability[TSchemaType](ContextualType contextualType, Boolean isNullable, JsonSchemaResolver schemaResolver, Action`2 transformation)
 at NSwag.Generation.OpenApiSchemaGenerator.GenerateWithReferenceAndNullability[TSchemaType](ContextualType contextualType, Boolean isNullable, JsonSchemaResolver schemaResolver, Action`2 transformation)
 at NJsonSchema.Generation.JsonSchemaGenerator.LoadPropertyOrField(JsonProperty jsonProperty, ContextualAccessorInfo accessorInfo, Type parentType, JsonSchema parentSchema, JsonSchemaResolver schemaResolver)
 at NJsonSchema.Generation.JsonSchemaGenerator.GenerateProperties(Type type, JsonSchema schema, JsonSchemaResolver schemaResolver)
 at NJsonSchema.Generation.JsonSchemaGenerator.GenerateObject(JsonSchema schema, JsonTypeDescription typeDescription, JsonSchemaResolver schemaResolver)
 at NSwag.Generation.OpenApiSchemaGenerator.GenerateObject(JsonSchema schema, JsonTypeDescription typeDescription, JsonSchemaResolver schemaResolver)
 at NJsonSchema.Generation.JsonSchemaGenerator.Generate[TSchemaType](TSchemaType schema, ContextualType contextualType, JsonSchemaResolver schemaResolver)
 at NJsonSchema.Generation.JsonSchemaGenerator.Generate[TSchemaType](ContextualType contextualType, JsonSchemaResolver schemaResolver)
 at NJsonSchema.Generation.JsonSchemaGenerator.GenerateWithReferenceAndNullability[TSchemaType](ContextualType contextualType, Boolean isNullable, JsonSchemaResolver schemaResolver, Action`2 transformation)
 at NSwag.Generation.OpenApiSchemaGenerator.GenerateWithReferenceAndNullability[TSchemaType](ContextualType contextualType, Boolean isNullable, JsonSchemaResolver schemaResolver, Action`2 transformation)
 at NSwag.Generation.AspNetCore.Processors.OperationParameterProcessor.AddBodyParameter(OperationProcessorContext context, ExtendedApiParameterDescription extendedApiParameter)
 at NSwag.Generation.AspNetCore.Processors.OperationParameterProcessor.Process(OperationProcessorContext operationProcessorContext)
 at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.RunOperationProcessors(OpenApiDocument document, ApiDescription apiDescription, Type controllerType, MethodInfo methodInfo, OpenApiOperationDescription operationDescription, List`1 allOperations, OpenApiDocumentGenerator swaggerGenerator, OpenApiSchemaResolver schemaResolver)
 at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.AddOperationDescriptionsToDocument(OpenApiDocument document, Type controllerType, List`1 operations, OpenApiDocumentGenerator swaggerGenerator, OpenApiSchemaResolver schemaResolver)
 at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateForControllers(OpenApiDocument document, IGrouping`2[] apiGroups, OpenApiSchemaResolver schemaResolver)
 at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateAsync(ApiDescriptionGroupCollection apiDescriptionGroups)
 at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GenerateDocumentAsync(HttpContext context)
 at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GetDocumentAsync(HttpContext context)
 at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
 at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

I do have models like the following, which seem to cause the problem:

```
[JsonConverter(typeof(StateValueJsonInheritanceConverter))]
[KnownType(typeof(StateValue<Boolean>))]
[KnownType(typeof(StateValue<Int32>))]
public abstract class StateValue
{
  // ...
}

public class StateValue<T> : StateValue
{
  // ...
}
```

**Comment by RicoSuter** [comment]
@rhegner this has already been fixed in nswag v13.13.1

**Comment by RicoSuter** [comment]
> I'm not sure exactly what this library does

It's a library with advanced .NET reflection APIs, i.e. to check nullability of properties (Nullable Reference Types) and XML Docs reading etc.

**Comment by rhegner** [comment]
Unfortunately I see the same behavior with version 13.13.0 and 13.13.1. Currently I'm stuck with 13.12.1.

**Comment by RicoSuter** [comment]
v13.13.2 should fix it soon

**Comment by billybraga** [comment]
Thanks for the quick fix. Seems to work fine.

**Comment by rhegner** [comment]
> v13.13.2 should fix it soon

v13.13.2 fixes my problem too. Thanks for the quick fix!!
